### PR TITLE
Fix type field path

### PR DESCRIPTION
**Pull request by smorimoto**
If I understand correctly, I think the previous PR had the wrong type field... I completely forgot to fix that. I believe this will eliminate any errors.

### CODE REVIEW

**Review by luwes — APPROVED** [review]
👍

**Comment by luwes** [comment]
thanks @smorimoto ! it seems better 
https://arethetypeswrong.github.io/?p=%40mux%2Fmux-player%401.11.4

but not all is good yet somehow
https://arethetypeswrong.github.io/?p=%40mux%2Fmux-player%401.11.4-canary.0-2197108

our web build checks passed. was a bit worried about the change to `type: module`
https://github.com/muxinc/web-build-checks/actions/runs/5659725527/job/15333912154

**Comment by smorimoto** [comment]
@luwes As for the web build checks, it seems like a private repository and I don't have access to it.

**Comment by luwes** [comment]
I think we might have to update moduleResolution. I'm doing some research

https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/InternalResolutionError.md#declarations-and-javascript-match-but-are-not-checked-with-correct-settings

**Comment by luwes** [comment]
it looks like it's trying to resolve `/helpers` in ESM mode but that requires `/helpers.js` to access the file in ESM.

SCR-20230725-imb

it's actually good practice to add the `.js` extension always, even in TS so ESM works when not bundling.

**Comment by smorimoto** [comment]
@luwes Is explicit support for older TypeScript mandatory in Mux?

**Comment by luwes** [comment]
I think version 4 is probably sufficient. @cjpillsbury do you know how far back we support?

**Pull request merged**
