### PR TITLE
Upgrade to CRA 5, rename cjs to .cjs.js

### PR DESCRIPTION
**Pull request by gkatsev**
Supersedes #210, inspired by #224

### CODE REVIEW

**Review by luwes — APPROVED** [review]
🚢 !

**Review by cjpillsbury — CHANGES_REQUESTED** [review]
blocker: has this been tested against CRA 4/older webpack? I noticed all cjs bundles were removed from the react packages, and I **_thought_** the assumption was cjs was expected for those cases.

**Comment by gkatsev** [comment]
@cjpillsbury it's because esm builds were added to the react packages. We can remove those, if we wanted.

Good call on trying it out with current CRA, let me try it out locally.

**Comment by gkatsev** [comment]
And I need to resolve the merge conflict again

**Comment by gkatsev** [comment]
CRA4 with the two changes: https://github.com/muxinc/elements/pull/227
Has the following error:
```
Can't import the named export 'StreamTypes' from non EcmaScript module (only default export is available)
```

**Comment by gkatsev** [comment]
I've removed the addition of the esm builds for the react packages because they seem to break CRA4.

**Comment by gkatsev** [comment]
The CRA build of vercel is now passing in https://github.com/muxinc/elements/pull/227: https://elements-demo-create-react-app-git-fork-gkatsev-cjs-798162-mux.vercel.app/

**Review by cjpillsbury — APPROVED** [review]
non-blocking nit: looks like I/you generated the updated CRA app w/npm instead of yarn so the docs changed. We should probably still recommend folks use yarn, but this is def lo pri.

Otherwise, looking 😎, tested across different apps.

**Pull request merged**
