### PR TITLE
Player error context

### PR DESCRIPTION
**Pull request by dylanjha**
* Mux Data Dashboard will group errors much better this way

### CODE REVIEW

**Review by luwes — APPROVED** [review]
LGTM

**Comment by dylanjha** [comment]
Doing some manual QA and I'm not seeing the expected context flow through to the Mux Dashboard, going to debug this a bit more

DO NOT MERGE!

**Comment by dylanjha** [comment]
Okay 😄 fixed now

**Review by luwes — APPROVED** [review]
👍

**Pull request merged**
